name: "Sync Fork Branch 17.0"

on:
  schedule:
    - cron: '0 */1 * * *' # on every hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: [self-hosted, linux, x64, btl]

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: ingadhoc
          github_token: ${{ secrets.FORK_SYNC_TOKEN }}
          personal_token: ${{ secrets.FORK_SYNC_SIREKO_TOKEN }}
          base: "17.0"
          head: "17.0"
          merge_method: merge
          pr_title: "Fork Sync Branch 17.0"
          auto_approve: true
